### ISSUE TITLE
Summoned tokens that share turns with summoner cannot be moved

### ISSUE THREAD

**Issue by jmack** [CDeenen/NotYourTurn#10]
Certain summoned tokens (spiritual weapon for example) do not have initiative slots and instead can be moved on their owners turn. NYT doesn't account for this, warning that it's not their turn and preventing movement. Ideally, tokens that are not in an encounter (not in turn order) should be exempt from NYT prompts.

**Comment by CDeenen** [comment]
I can add an option in the module settings to choose that

**Comment by CDeenen** [comment]
I'm not sure why this issue is still open, I believe this has been possible for a long time now, by disabling 'block non combat movement' using the control buttons
