### ISSUE TITLE
Movement restrictions stop working when switching scenes

### ISSUE THREAD

**Issue by Wocowoco** [CDeenen/NotYourTurn#13]
Whenever Foundry gets loaded for the first time (the first scene that gets loaded), the movement restrictions work as intended for both GM and players.
As soon as a player/GM swaps to a new scene (themselves, or being dragged by DM), their movement restrictions no longer apply within the new scene. When swapping back to the previous scene, they are also able to move freely there.

If a player refreshes their browser on the new Scene, the movement restrictions will be re-applied to them, until they change scenes again.

**Comment by CDeenen** [comment]
Thanks for the bug report, I'll look into it.

**Comment by CDeenen** [comment]
This should be fixed in the latest version (v1.1.3)
