### ISSUE TITLE
Functionality lost.

### ISSUE THREAD

**Issue by ABrandau** [CDeenen/NotYourTurn#16]
Hello, been using this module for a while, it worked fine 2 weeks ago, but lately i updated everything (module list, 5e system, foundry) and the module does not work at all, it does not block movement nor throw warnings, 

This is the configuration that i have for the module: 

![image](https://user-images.githubusercontent.com/11763228/115132616-c65d9300-9fcf-11eb-989c-8b533077e5f4.png)

I tested the module alone and I could still move tokens as a played while it isnt my turn.

Edit: Version 1.13 works as it should.

**Comment by CDeenen** [comment]
Hey, the last update for Not Your Turn was almost 2 months ago. In that time I have not noticed any issues, and nobody else has reported something similar, so I'm a bit confused why it doesn't work for you. 
I'll have a look later today, to make sure that it actually still works. 
Btw, I'm assuming you haven't updated Foundry to 0.8.x yet. 0.8 shouldn't be used by anyone except developers and testers at the moment. Not Your Turn isn't compatible with 0.8 yet.

**Comment by ABrandau** [comment]
Yes, foundry version is 0.7.9 and 1.2.4 I believe, the version i had before updating must have been 2 or 3 months old, i updated the module a couple times and the bug persists, if I downgrade manually the bug is solved, but now that I tested for a third time, the module does not recognize when its in combat and when it isnt, so its always blocking movement, i recall i updated the module a couple of weeks ago because of that problem to begin with.

**Comment by CDeenen** [comment]
You might have missed that in the last update I added a control button to easily switch movement blocking on and off.
It's added to the basic controls (top left button), and there are 2 buttons, one to block movement during combat (hand icon), and one outside combat (lock icon)

**Comment by ABrandau** [comment]
Alright i double checked with the newest version and after seeing and using the button, I cannot repeat any of the bugs I had before on older versions, sorry for taking your time.

**Comment by CDeenen** [comment]
No problem, happy it works now!
