### ISSUE TITLE
[BUG] Movement skips during combat

### ISSUE THREAD

**Issue by ghost** [CDeenen/NotYourTurn#17]
**Setup**
 - OS: [e.g. windows]
 - Browser: Chrome
 - Module version: 1.1.5
 - Foundry version: 0.8.6 / 0.8.7
 - Gaming system & version: dnd5e 1.3.5
 - Any other modules enabled: no (but happens more often if "Drag Ruler" is installed and enabled)

**Describe the bug**
When dragging a token using Ctrl+Drag+Space while in active combat, movement is very jumpy.

Additionally, when the "Drag Ruler" module is enabled, it always happens when dragging (originally reported in https://github.com/manuelVo/foundryvtt-drag-ruler/issues/84).

**Screenshots**
Just the module by itself, using Ctrl+Drag+Space:
![20210618_142211](https://user-images.githubusercontent.com/7376474/122567594-bb12fc00-d040-11eb-99f1-421c7df97e48.gif)

With "Drag Ruler" enabled, simply dragging:
![20210616_213658](https://user-images.githubusercontent.com/7376474/122289966-2ea2f500-ceeb-11eb-8a9b-dc461d200808.gif)

**Console Log**
There is a warning constantly being triggered while "Not Your Turn" is active, but I'm not sure if it's related:

![image](https://user-images.githubusercontent.com/7376474/122567784-f6adc600-d040-11eb-984d-228382b37baf.png)

**Additional context**
The problem never happens if "Not Your Turn" is disabled.

**Comment by CDeenen** [comment]
Thanks for the issue report.
I can reproduce this issue, so I'll see what I can do to fix it.

**Comment by STBaf** [comment]
Reworked the position saving. Hopefully resolved a while ago by rework
