### ISSUE TITLE
[BUG] When GM moves tokens who do not have initiative, tokens move on their own

### ISSUE THREAD

**Issue by jhymesba** [CDeenen/NotYourTurn#18]
**Setup**
 - OS: Windows
 - Browser: Edge
 - Module version: [e.g. 1.2.5]
 - Foundry version: 0.8.8
 - Gaming system & version: GURPS 0.11.3
 - Any other modules enabled: yes

**Describe the bug**
When attempting to move groups of NPC tokens, tokens will start moving everywhere, generating repeated error messages and causing the screen to jump from place to place. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4042155/124031705-e12b8b00-d9b4-11eb-90f3-60df5260b099.png)

![image](https://user-images.githubusercontent.com/4042155/124031753-f0aad400-d9b4-11eb-8e6c-36c2a9f4e83f.png)

![image](https://user-images.githubusercontent.com/4042155/124031797-fdc7c300-d9b4-11eb-92b2-f97be1b44bef.png)

It's really difficult to give a good view of this without doing a video, but these are just three images. 

**Console Log**
foundry.js:19259 You are calling PlaceableObject#getFlag which has been deprecated in favor of Document#getFlag. Support will be removed in 0.9.0
getFlag @ foundry.js:19259
blockMovement @ NotYourTurn.js:187
(anonymous) @ NotYourTurn.js:157
_call @ VM5873:4
callAll @ foundry.js:153
callback @ foundry.js:8880
(anonymous) @ foundry.js:8850
_handleUpdateEmbeddedDocuments @ foundry.js:8850
_updateEmbeddedDocuments @ foundry.js:8739
3foundry.js:19241 You are calling PlaceableObject#update which has been deprecated in favor of Document#update or Scene#updateEmbeddedDocuments. Support will be removed in 0.9.0
update @ foundry.js:19241
setTokenPositionNew @ misc.js:51
blockMovement @ NotYourTurn.js:228
(anonymous) @ NotYourTurn.js:157
_call @ VM5873:4
callAll @ foundry.js:153
callback @ foundry.js:8880
(anonymous) @ foundry.js:8850
_handleUpdateEmbeddedDocuments @ foundry.js:8850
_updateEmbeddedDocuments @ foundry.js:8739
foundry.js:19268 You are calling PlaceableObject#setFlag which has been deprecated in favor of Document#setFlag. Support will be removed in 0.9.0
setFlag @ foundry.js:19268
setTokenPositionNew @ misc.js:52
6foundry.js:19241 You are calling PlaceableObject#update which has been deprecated in favor of Document#update or Scene#updateEmbeddedDocuments. Support will be removed in 0.9.0

(repeated)

**Additional context**

**Comment by STBaf** [comment]
Since this bug is a little bit ago and we already arrived v9 stable: Can you still reproduce this problem or seem to be gone away by itself ?

**Comment by STBaf** [comment]
old issue, not clear if still exist, closing
