### ISSUE TITLE
Italian Localization

### ISSUE THREAD

**Issue by smoothingplane** [CDeenen/NotYourTurn#23]
Hi, I translated your module into Italian, I am sending you the files!
[it.zip](https://github.com/CDeenen/NotYourTurn/files/7802871/it.zip)

**Comment by STBaf** [comment]
Thank you for your contribution :). I will take a look at it soon and include it in the project if ok.

**Comment by smoothingplane** [comment]
Sure!

**Comment by STBaf** [comment]
Your module translation was included into the code and a new version was released. Again, thank you for your contribution.
