### ISSUE TITLE
Movement becomes bugged after first pop-up window for player

### ISSUE THREAD

**Issue by JakeMilo** [CDeenen/NotYourTurn#26]
Hi,

I will try to describe the issue:

Setup: 
I installed Not Your Turn.
I placed two tokens (A and B) representing characters on a map in a scene.
I started an encounter with those two tokens. 

When it is token A's turn I try to move token B.
The dialog box opens, asking if I would like to ask gm or cancel. 

If I cancel the move the token becomes stuck. -->
Stuck meaning that trying to move token B again does not re-open the dialog box. When the turn becomes Token B turn, token B still cannot move. 
Coming out of combat stop this, but if I restart the combat Token B gets dragged back to the "stuck" position.

**Comment by JakeMilo** [comment]
Oh yes: Foundry Version 9 - Build 249

**Comment by erlendaakre** [comment]
Having the same issue, if the dialog box to prevent out of turn movement comes up and the user clicks `Undo` then the player can not move again without reloading the webpage.

If the user clicks `Request` and the GM rejects the request, then there is no issue.

Player error when clicking `Undo`:

```
misc.js:38 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'set')
[Detected 1 package: NotYourTurn]
    at setTokenPositionOld (misc.js:38:17)
    at async undoMovement (misc.js:56:5)
setTokenPositionOld @ misc.js:38
await in setTokenPositionOld (async)
close @ NotYourTurn.js:284
close @ foundry.js:44084
submit @ foundry.js:44073
_onClickButton @ foundry.js:44035
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

**Comment by STBaf** [comment]
Thanks for the detailed error description. I will take a look into it and hopefully can provide a fix soon. Please be patient some days :)

**Comment by STBaf** [comment]
I correct - the error is obvious - I missed a code change with the last update *facepalm* ok sorry - I have a game session this evening, after that I will fix it tomorrow

**Comment by erlendaakre** [comment]
great to see the fix before tomorrow's session :D , cheers 💯
