### ISSUE TITLE
[Feature request] Add multilanguage support

### ISSUE THREAD

**Issue by lozalojo** [CDeenen/NotYourTurn#3]
Please add the framework for translating the module to other languages (as other modules do, with an en.json file in a lang folder with keys that we can translate).

I have translated more than 10 modules and this one doesnt support translating.

Thanks and great work!

**Comment by CDeenen** [comment]
I'll look into it once I have time, probably in a few days.

**Comment by lozalojo** [comment]
Great, thank you!

**Comment by CDeenen** [comment]
It's been added to the latest version.
Please let me know if I've missed any strings

**Comment by lozalojo** [comment]
This evening I will take a look at the translation and will send you a PR.

Thank you!

**Comment by lozalojo** [comment]
Just sent PR for spanish translation!

**Comment by CDeenen** [comment]
Thanks!
I've accepted and merged the changes.
How would you like to be credited? (name, contact, etc)

**Comment by lozalojo** [comment]
The nickname of github, lozalojo

Thanks!
