### ISSUE TITLE
[0.75] Module request to move even when it is the player's turn

### ISSUE THREAD

**Issue by devnagui** [CDeenen/NotYourTurn#7]
![image](https://user-images.githubusercontent.com/19239974/97219497-029efc00-17c2-11eb-9110-ebe650f30e22.png)

**Comment by CDeenen** [comment]
What Foundry version are you using? And could you try disabling all other modules and see if you get the same issue?

**Comment by devnagui** [comment]
Ill double check if the problem is on the other modules.

**Comment by CDeenen** [comment]
There's compatibility issues with the module Enhanced Movement, are you using that by any chance?

**Comment by devnagui** [comment]
Nope, disabled all modules, still happening since I've updated to 0.75:
![image](https://user-images.githubusercontent.com/19239974/97220144-efd8f700-17c2-11eb-8e4d-4681dfc38c68.png)

**Comment by devnagui** [comment]
I imagine that tidy ui wont matter, right?

**Comment by CDeenen** [comment]
Tidy UI probably doesn't matter, but you're using Not Your Turn v1.0.0
Could you please update to v1.0.3 and try again?

**Comment by devnagui** [comment]
sure, funny, I just issue an update for all modules...

**Comment by CDeenen** [comment]
That's weird. Maybe try uninstalling the module, and then reinstalling it?

**Comment by devnagui** [comment]
Weird! I'm going to reinstall from scratch.
![image](https://user-images.githubusercontent.com/19239974/97220753-df754c00-17c3-11eb-83d6-4035131210a4.png)

**Comment by devnagui** [comment]
Version update worked. All good, thanks!

**Comment by CDeenen** [comment]
That is weird, indeed.
Good to hear it's working now, though!
