### ISSUE TITLE
[Feature] Add an "Exploration Mode"

### ISSUE THREAD

**Issue by lozalojo** [CDeenen/NotYourTurn#8]
Since NotYourTurn works only in combat, I'd suggest adding a configuration toggle "Exploration Mode".

Config:
Enable Exploration Mode: on/off
Key to enable EM: CTRL+1

In Exploration Mode all tokens are locked and must request permission to move (as in combat). This denies the players to begin exploration and see the map, alllowing the GM to trigger events when someones enter an area.

If possible, also might be a button to enable/diable in the left quick bar.

**Comment by CDeenen** [comment]
That shouldn't be a problem, I'll look into it once I have the time

**Comment by lozalojo** [comment]
Yes. that is what I thought, you have all the hard work done, just make adjustements to make it work in a non combat environment, this enhancement would be of a great help, imho.

**Comment by CDeenen** [comment]
Please check the latest version (you have to uninstall the previous version before you can update to this one, due to a mistake I made).
I've added a button to the 'Basic Control' on the left, called 'Block Movement'. Pressing this will block movement outside of combat. I'll add a hotkey for it later.

**Comment by CDeenen** [comment]
Btw, what should the Spanish translation be for the name of the 'Block Movement' button?

**Comment by lozalojo** [comment]
Literally, "Bloquear Movimiento", but wait, I've seen you've made some other changes to en.json, I'll take a look and send a PR within an hour or so to fix all changes, I have to keep track of all of them.

Thank you for your quick response!

**Comment by lozalojo** [comment]
Done! PR sent, not so many changes, I thought I saw references to the block movement feature in the descriptions
